[Issue #7] Only bind-mount extant qemu binaries
resin-io/docker pull request #8
Opened 2016-09-22 00:19 UTC by brownjohnf

Connects to #7 

If you ran a build without the qemu binaries on the host, it created an empty directory with the name of the binary inside the built image. If you then attempt to run that image, build anything based on that image, or run anything built on that base image on a host with the correct binaries docker complains because you're attempting to mount a file onto a directory.

2016-09-22 00:22 UTC, brownjohnf commented on builder/dockerfile/internals.go
> +		if _, err := os.Stat(mount); err == nil {
I suppose we should probably check that it's a file, and not just present.

2016-09-22 00:23 UTC, brownjohnf commented on builder/dockerfile/internals.go
> +			fmt.Fprintf(b.Stdout, " ---> Adding bind mount during build: %s\n", toAdd)
These will be printed to the terminal on a build; not sure if a) we want to clutter the output and b) want to advertise that we're doing this.

2016-09-22 00:23 UTC, petrosagg commented on builder/dockerfile/internals.go
> +			fmt.Fprintf(b.Stdout, " ---> Adding bind mount during build: %s\n", toAdd)
I think we'd prefer these logs to be in docker's logs, not in the build output. You can use `logrus.Debugf` or some other log level. See the lines above

2016-09-22 00:25 UTC, petrosagg requested changes

2016-09-22 00:26 UTC, Page- commented on builder/dockerfile/internals.go
> +			fmt.Fprintf(b.Stdout, " ---> Adding bind mount during build: %s\n", toAdd)
Yeah, I think this would look a bit awkward in the build logs of a git push

2016-09-22 00:26 UTC, Page- commented on builder/dockerfile/internals.go
> +		if _, err := os.Stat(mount); err == nil {
I agree, I'd rather check specifically for a file

2016-09-22 00:27 UTC, Page- requested changes

2016-09-22 00:28 UTC, petrosagg commented on builder/dockerfile/internals.go
> +		if _, err := os.Stat(mount); err == nil {
This is very easy if you've already done a Stat:
```golang
stat, err := os.Stat(mount)
if !stat.IsDir() {
 ...
}
```

2016-09-22 00:29 UTC, petrosagg commented on builder/dockerfile/internals.go
> +		if _, err := os.Stat(mount); err == nil {
or `stat.Mode().IsRegular()`

2016-09-23 15:36 UTC, brownjohnf commented
I believe I've addressed your concerns, but this new github review thing is confusing.

2016-09-23 23:06 UTC, Page- approved these changes

2016-09-26 18:01 UTC, brownjohnf commented
@petrosagg can you give this a final review?

2016-09-27 05:15 UTC, petrosagg approved these changes

2016-09-28 08:30 UTC, petrosagg commented
@brownjohnf at least for the resin builder this will be superseded by this commit https://github.com/resin-io/docker/commit/9d155107b06c7f96a8951cbbc18287eeab8f60cc . It allows to specify bind mounts through the Docker API and CLI and do things like `docker build -v /foobar:/usr/src/app .`.

What do you think we should do for jenkins? We could leave it up to the build jobs to decide if they want to have qemu bind mounted. The other option I've thought of is adding a simlar parameter to the `docker daemon` command that will define global, default bind mounts. This way it will be configurable through the CLI, not require changes in the jenkins jobs side and won't have hardcoded paths.

2016-09-28 15:50 UTC, closed without merging

2016-09-28 15:57 UTC, brownjohnf commented
@petrosagg, a couple things:

1) I think we need to have a better, more transparent development process for this stuff. It's really frustrating to have PRs into branches that you're just modifying and force-pushing, and it makes it more time-consuming than necessary to watch what you're doing. Why can't you do this work in a feature branch, and PR it into resin-1.12.x?

2) Regarding Jenkins, we have some jobs that need and some that don't, so I think each job should have to explicitly mount whatever volumes they want. For example, building the supervisor with the qemu bind-mount enabled fails.

2016-09-28 20:39 UTC, petrosagg commented
@brownjohnf `resin-1.12.x` _is_ my feature branch, it didn't exist 2 days ago and there was nowhere to PR onto. The fix that Ι backported there was merged upstream on Monday which is when I started working on it. So I think it's ok to force-push my WIP branch. A PR on resin-release would mean thousands of changes as this PR currently has. My branch is only referenced by another PR that is under review currently https://github.com/resin-io/resin-builder/pull/22

On jenkins, I'm only worried that our build scripts will invoke `docker build` with a parameter that doesn't exist upstream so if someone were to run them it would complain. Not sure if this is something we should care about but that's the only downside from what I can see